# Generated by Django 4.2.7 on 2023-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateWinnerExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('partners', 'Partners'), ('fls', 'FLS')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
